export const TABLE_RESIZE = 'TABLE_RESIZE'
export const TABLE_INPUT = 'TABLE_INPUT'
export const TABLE_STYLE = 'TABLE_STYLE'
export const HEADER_INPUT = 'HEADER_INPUT'
export const CHANGE_TIME = 'CHANGE_TIME'